chore: add linter to the project
training-center/hades pull request #24
Opened 2017-12-29 00:22 UTC by vcapretz

I used xo for that, which is supposed to run with almost none configs,
but some changes were necessary to this project

- the indent rule is off because of a eslint bug:
https://github.com/eslint/eslint/issues/9779

I added the `.editorconfig` to help us formatting files 

closes #23

2018-01-03 17:35 UTC, lflimeira requested changes

2018-01-03 17:35 UTC, lflimeira commented on test/acceptance/index.js
> +					const expected = 'Plataforma training-center';
@vcapretz acho que deu ruim aqui.

2018-01-03 17:35 UTC, lflimeira commented on daos/areasDAO.js
> -const models = require("../models/");
Você removeu esse arquivo?

2018-01-03 17:35 UTC, lflimeira commented on test/acceptance/areas.js
> +	it('GET areas/ - retorna lista de areas vazia', done => {
Aqui está utilizando tab, e em outros arquivos utiliza espaço.

2018-01-03 17:39 UTC, lflimeira commented
Eu estava pensando em usar o da Airbnb https://github.com/airbnb/javascript o que vc acha?

2018-01-03 17:52 UTC, vcapretz commented on daos/areasDAO.js
> -const models = require("../models/");
apenas renomeei, porque uma sugestão do eslint default é arquivos em snake-case

2018-01-03 17:52 UTC, vcapretz commented
vou trocar entao e tirar o xo, colocar o eslint padrão e extender airbnb haha

2018-01-04 11:23 UTC, vcapretz commented
@lflimeira done! troquei o linter e as regras dele pra um mais padrão a lá Airbnb

2018-01-04 17:18 UTC, lflimeira approved these changes

2018-01-04 17:18 UTC, lflimeira commented on daos/areasDAO.js
> -const models = require("../models/");
Boaaa =)

2018-01-04 17:18 UTC, merged